name: TEST Pull Request Trigger for Issue 2592
on:
  pull_request:
    types: [closed]
    branches:
      - 'gh-pages'
      - 'feature-homepage-launch'

jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
     - run: echo "ðŸº This is the 'TEST Pull Request Trigger for Issue 2592' job, automatically triggered by a ${{ github.event_name }} event."
          
  TEST-Does-This-Work-1:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    steps:
     - run: echo "I am running because ***github.event_name == 'pull_request' && github.event.pull_request.merged == true'***."
  
  TEST-Does-This-Work-2:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true}}
    steps:
     - run: echo "I am running because only --> github.event.pull_request.merged == true <--."

  Delete-Merged-PRs:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }} 
    steps: 
      - name: Delete Merged PRs
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: 'Project Board'
          column: 'TEST 2592'
          repo-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
          action: delete
          

          
